### ISSUE TITLE
npm install dependency issue with webpack

### ISSUE THREAD

**Issue by GavinRooney** [aws-samples/amazon-chime-sdk-amazon-connect-integration-demo#4]
There is an error when running npm install as guided here

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: connect@1.0.0
npm ERR! Found: webpack@4.44.2
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^4.42.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^3.1.0" from extract-text-webpack-plugin@3.0.2
npm ERR! node_modules/extract-text-webpack-plugin
npm ERR!   dev extract-text-webpack-plugin@"^3.0.2" from the root project

**Comment by cardright** [comment]
I had to run  webpack-cli init

**Comment by michhyun1** [comment]
I was able to clone the repo and do npm install for both the agent and customer. Could you please give some more details on what steps you took to get this error? Thanks.

**Comment by devalevenkatesh** [comment]
I tried re-installing the `/agent` and `/customer` apps as instructed in the README. I did not found the stated error. One reason may be the `extract-text-webpack-plugin` and `webpack` version. This plugin was deprecated in Webpack 4. You can try removing `extract-text-webpack-plugin` from `package.json` of both apps since we do not use it anyway. Both the apps use the updated and recommended `mini-css-extract-plugin`. You can check this [Webpack issue comment](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/749#issuecomment-374549467) for more information. 

Closing the issue. Please feel free to re-open if you still face the issue.
